use serde_json::json;

use crate::profile::{PlatformTarget, WebsiteProfile};

pub fn render_package_json(package_name: &str) -> String {
    format!(
        r#"{{
  "name": "{package_name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite --host 127.0.0.1",
    "build": "tsc --noEmit && vite build",
    "tauri": "tauri",
    "bundle": "tauri build"
  }},
  "dependencies": {{
    "@tauri-apps/api": "^2.0.0"
  }},
  "devDependencies": {{
    "@tauri-apps/cli": "^2.0.0",
    "typescript": "^5.5.0",
    "vite": "^5.3.0"
  }}
}}
"#
    )
}

pub fn render_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "strict": true,
    "noUncheckedIndexedAccess": true
  },
  "include": ["src"]
}
"#
    .to_string()
}

pub fn render_vite_config() -> String {
    r#"import { defineConfig } from "vite";

export default defineConfig({
  clearScreen: false,
  server: {
    strictPort: true,
    host: "127.0.0.1",
    port: 1420
  },
  envPrefix: ["VITE_"],
  build: {
    minify: "esbuild",
    sourcemap: false,
    target: "es2022",
    rollupOptions: {
      treeshake: true
    }
  }
});
"#
    .to_string()
}

pub fn render_index_html(product_name: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
"#,
        html_escape(product_name)
    )
}

pub fn render_cargo_toml(package_name: &str) -> String {
    let rust_name = package_name.replace('-', "_");
    format!(
        r#"[package]
name = "{rust_name}"
version = "0.1.0"
description = "Generated by PICO"
authors = ["PICO"]
edition = "2021"
rust-version = "1.78"

[lib]
name = "{rust_name}_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = {{ version = "2", features = [] }}

[dependencies]
tauri = {{ version = "2", features = [] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"
panic = "abort"
strip = true
"#
    )
}

pub fn render_build_rs() -> String {
    r#"fn main() {
    tauri_build::build();
}
"#
    .to_string()
}

pub fn render_tauri_main(rust_crate_name: &str) -> String {
    format!(
        r#"fn main() {{
    {rust_crate_name}_lib::run();
}}
"#
    )
}

pub fn render_tauri_lib(profile: &WebsiteProfile) -> String {
    let target_url = serde_json::to_string(profile.website_url.as_str()).expect("url serializes");

    format!(
        r#"use tauri::Manager;

const TARGET_URL: &str = {target_url};

#[tauri::command]
fn target_url() -> &'static str {{
    TARGET_URL
}}

pub fn run() {{
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![target_url])
        .setup(|app| {{
            if let Some(window) = app.get_webview_window("main") {{
                window.set_focus()?;
            }}

            Ok(())
        }})
        .run(tauri::generate_context!())
        .expect("failed to run generated PICO application");
}}
"#
    )
}

pub fn render_tauri_conf(
    profile: &WebsiteProfile,
    _package_name: &str,
    product_name: &str,
    _icon_hash: &str,
) -> Result<String, serde_json::Error> {
    let mut bundle = json!({
        "active": true,
        "targets": bundle_targets(profile),
        "publisher": "PICO",
        "category": "Productivity",
        "shortDescription": profile.app.description.as_deref().unwrap_or(product_name),
        "longDescription": profile.app.description.as_deref().unwrap_or(product_name),
        "copyright": "Copyright PICO",
        "icon": [
            "icons/32x32.png",
            "icons/128x128.png",
            "icons/128x128@2x.png",
            "icons/icon.icns",
            "icons/icon.ico"
        ],
        "resources": [
            "icons/splash.png"
        ],
        "windows": {
            "webviewInstallMode": {
                "type": "downloadBootstrapper"
            }
        },
        "macOS": {
            "minimumSystemVersion": "11.0",
            "hardenedRuntime": true,
            "entitlements": null
        },
        "linux": {
            "deb": {
                "depends": []
            }
        },
        "externalBin": []
    });

    if profile
        .auto_update
        .as_ref()
        .map(|u| u.enabled)
        .unwrap_or(false)
    {
        bundle["createUpdaterArtifacts"] = json!(true);
    }

    let config = json!({
        "$schema": "https://schema.tauri.app/config/2",
        "productName": product_name,
        "version": profile.app.version,
        "identifier": profile.app.bundle_identifier,
        "build": {
            "beforeDevCommand": "bun run dev",
            "devUrl": "http://127.0.0.1:1420",
            "beforeBuildCommand": "bun run build",
            "frontendDist": "../dist"
        },
        "app": {
            "security": {
                "csp": csp(profile),
                "assetProtocol": {
                    "enable": false
                }
            },
            "windows": [{
                "label": "main",
                "title": product_name,
                "width": 1200,
                "height": 800,
                "minWidth": 720,
                "minHeight": 480,
                "resizable": true,
                "fullscreen": false,
                "center": true
            }]
        },
        "bundle": bundle
    });

    serde_json::to_string_pretty(&config).map(|json| format!("{json}\n"))
}

pub fn render_build_platform() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail

platform="${1:-}"
if [[ -z "${platform}" ]]; then
  echo "usage: scripts/build-platform.sh <windows|macos|linux>" >&2
  exit 64
fi

case "${platform}" in
  windows)
    bun install --frozen-lockfile
    bun run tauri build -- --bundles nsis,msi
    ;;
  macos)
    bun install --frozen-lockfile
    bun run tauri build -- --bundles app,dmg
    ;;
  linux)
    bun install --frozen-lockfile
    bun run tauri build -- --bundles appimage
    ;;
  *)
    echo "unsupported platform: ${platform}" >&2
    exit 64
    ;;
esac
"#
    .to_string()
}

pub fn render_build_all() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail

case "$(uname -s)" in
  Linux*) scripts/build-platform.sh linux ;;
  Darwin*) scripts/build-platform.sh macos ;;
  MINGW*|MSYS*|CYGWIN*) scripts/build-platform.sh windows ;;
  *) echo "unsupported host platform" >&2; exit 69 ;;
esac
"#
    .to_string()
}

pub fn render_readme(profile: &WebsiteProfile, product_name: &str) -> String {
    format!(
        r#"# {product_name}

Generated by PICO from `{}`.

## Build

```bash
bun install --frozen-lockfile
scripts/build-all.sh
```

Platform-specific builds:

```bash
scripts/build-platform.sh windows
scripts/build-platform.sh macos
scripts/build-platform.sh linux
```

Windows builds produce NSIS `.exe` and `.msi` installers on Windows workers.
macOS builds produce `.app` and `.dmg` artifacts on macOS workers.
Linux smoke builds produce `.AppImage` artifacts. Debian and RPM packaging should be validated after the AppImage path is stable.
"#,
        profile.website_url
    )
}

fn bundle_targets(profile: &WebsiteProfile) -> Vec<&'static str> {
    let mut targets = Vec::new();
    for target in &profile.build_targets {
        match target.platform {
            PlatformTarget::Windows => {
                targets.push("nsis");
                targets.push("msi");
            }
            PlatformTarget::Macos => {
                targets.push("app");
                targets.push("dmg");
            }
            PlatformTarget::Linux => {
                targets.push("appimage");
                targets.push("deb");
                targets.push("rpm");
            }
        }
    }
    targets.sort_unstable();
    targets.dedup();
    targets
}

fn csp(profile: &WebsiteProfile) -> String {
    let origin = format!(
        "{}://{}",
        profile.website_url.scheme(),
        profile.website_url.host_str().unwrap_or_default()
    );
    format!(
        "default-src 'self' {origin}; connect-src 'self' {origin} https: wss:; img-src 'self' {origin} https: data:; script-src 'self' {origin}; style-src 'self' {origin} 'unsafe-inline'; font-src 'self' {origin} https: data:; frame-src {origin}; object-src 'none'; base-uri 'self'"
    )
}

fn html_escape(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
